### ISSUE TITLE
running `npx @rei/create-package@^2` produces error

### ISSUE THREAD

**Issue by daviduffy** [rei/create-package#15]
When running `npx @rei/create-package@^2` the tool starts to run, but ultimately fails on the `npm install` step where it encounters the following error:

```
'@rei/alpine-satchel-cleaner@^1.0.0' is not in this registry
```

It looks like when the create-package script runs, it may not create the `.npmrc` file that is required to allow `npm i` to complete properly.

**Comment by HeavyMedl** [comment]
Thanks for reporting this, @daviduffy. We had a similar issue with `.gitignore` not getting packed into the tarball that ends up in the NPM registry. I'm guessing a newer version of NPM (>8) is doing the same thing with `.npmrc`.

**Comment by HeavyMedl** [comment]
This should be fixed with the latest publish

```sh
$ npx @rei/create-package@latest
```
